---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-4"
    checks:
      # This appears to be borked in Code Climate’s config
      import/extensions:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- coverage/
- dist/
- node_modules/
- test/
- docs/
