language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8'
- '7'
- '6'
before_script:
- npm prune
- npm i codacy-coverage
after_success:
- npm run build
- npm run semantic-release
- npm test -- --coverage
- cat ./coverage/lcov.info | $(npm bin)/codacy-coverage
- rm -rf ./coverage
branches:
  only:
  - master
  - /^greenkeeper/.*$/
env:
  global:
    secure: GC9Q+9+h80eX2z3RE642lkO8hqEVAJLOD3bq33Uo3NtB4iE+naNZfpyhhdpZaLZf1DlqHEaPNOvMHmX6PxoVneXuEasaooJhax1dXhdzHBcZc6CjV/H19qr3+kSSu4vWIdqfX+8LIwPf3weR+d7PSvs+RFnFNeS6NRWgX9Hpmg4e5KHxzvhRxjX3DEhQ9+ixKWt80GozYqbc/dIF76f5x8kc9XH98sXn3X60NMlV7dDCuvqJnXN2T2mA9+bFTdnRfa86PmNbm8E9O9vg0Q2EgzAw5/MV1R6kHpaa0gUjkSgu0pQCQMQ96wo66YWa0cPHxScE53bIAHeqlZ3lwXDhOeTVeLac9xKW8vYDwmra75MOpKcuZTu10HW6PxzioJ43PJ2HVKkmcWVMOgpAcOeD9SiUj96/xmPXU0IN7EFWbdTW0qukoVL5Mn9jbOpdLbmZXddjF+ks/STvG0AW2cER4Cr6631vLANtwxLGhivBMujgJ9c43+EOAtl685zOCFRoWP5rI+la4elLwzvfaOidrtBncBJKPE2WVx+InLPxBOe9lLzniBgA0q0gdHWgnRuROfcQd0jUjomk/qjZ4q8u87e8pVCT6UA3YqJcBuCv8cljks0Ennbb+LbJjfQTGASwPOBlocAjloW6F8T3GvY+jZRoC0mBcJWHXd4sMmK8JEo=
