language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '6'
- '7'
- '8'
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    before_script:
    - npm prune
    - npm i codacy-coverage
    after_success:
    - npm run build
    - npm run semantic-release
    - npm test -- --coverage
    - cat ./coverage/lcov.info | $(npm bin)/codacy-coverage
    - rm -rf ./coverage
  - stage: deploy
    node_js: "8"
    script: npm run build && npm run semantic-release
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
env:
  global:
    secure: Y7CCsj1gAYuQ9xMarN31ltryv5OeREgAowl0FvBgHH/sC+bB2rw4eOQB4Qkm7lVACbJRd3CNfI0OrTmwdEGpTN5b3FJ1x6V0T7xv/76AdBzTvJ9fH7lH4SDIo4tUAT9CFPi263xPae337r7FuldoLFQzW/j3y5DnejYtKZaOokwELJLytFwLC6rLHXfrFeXHkItuMK3DfKmJAp4AIjVSSjpLPcdzZsxvf6POeX7Dw1jbk2PmApTY80x25HLdpGQHryw2oIBdImfmfsIlF0i1593P23bOlcxXtcRpsrbhkKlHc8Lw5xcj6JsfJ3VxXdawplw6GPrJ6CWJUhcOuYvv0D1CdfuucGECtD1DFppvqU9oZGs6pzQu20NYbn4snLYWQqyWWC2FEs8SkAK2aXF8klATDfrLcD9u+p2FQMW3nJq8xj/rzM1mnzWgdMCVwgCsQg8esTI9c0u3J2I1CJ1wWqrqONsQ7uhsfe12uwGVqlIvNM9I6RTc9PTCCtspuR0jErZc8sRJKXDExzoI/BCxlpVTGtwlboV02fyB4w3PYKFAAQ3D83ks7nKLJ75zKErBLSiFJWF0/z8nMOffq+HcXbr5PP1ycvVHQvZ7WjDUxMuvsUsUYmPZZ81bLc9lIDuvnxTRq+nP8EqsOHwsaARcu+QSYAGV/wklIUP/mWC9Cm4=
